update_wakewords:
  description: "Update the wakewords from the repository."
  fields:
    repository_url:
      description: "The URL of the repository containing wakewords."
      example: "https://github.com/fwartner/home-assistant-wakewords-collection"
      required: true
      selector:
        text:
    folder:
      description: "The folder within the repository containing the wakewords (optional)."
      example: "en"
      required: false
      selector:
        text:
    update_interval:
      description: "Enter the update interval in hours."
      example: 24
      required: false
      selector:
        number:
          min: 1
          max: 168
