update_wakewords:
  description: "Update the wakewords from the repository."
  fields:
    repository_url:
      description: "The URL of the repository containing wakewords."
      example: "https://github.com/fwartner/home-assistant-wakewords-collection"
      required: true
      selector:
        text:
    folder_path:
      description: "The folder within the repository containing the wakewords (optional)."
      example: "en"
      required: false
      selector:
        text:
    scan_interval:
      description: "Enter the scan interval in seconds."
      example: 3600
      required: false
      selector:
        number:
          min: 1
          max: 86400
